[package]
name = "void"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
mockall = "0.11.0"
anyhow = "1.0.56"
chrono = "0.4.19"

[dependencies.tokio]
version = "1.17.0"
features = ["macros", "rt-multi-thread"]

[dependencies.sqlx]
version = "0.5.11"
features = ["runtime-tokio-rustls", "postgres", "uuid", "macros", "migrate", "time", "offline"]

[dependencies.serenity]
version = "0.10.10"
default-features = true
