version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=void-db
      - POSTGRES_PASSWORD=secret

  void-bot:
    build:
      context: .
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - target/
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TOKEN=${TOKEN}  
      - PREFIX=${PREFIX}
      - ENABLE_WHITESPACE=${ENABLE_WHITESPACE}
      - CHANNEL_ID=${CHANNEL_ID}
      - GUILD_ID=${GUILD_ID}
      - APP_ID=${APP_ID}
      - MODE=${MODE}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: